name = "mi-health-mcp"
main = "src/index.js"
compatibility_date = "2026-08-24"
workers_dev = true

[observability]
enabled = true
head_sampling_rate = 1

[[kv_namespaces]]
binding = "MI_HEALTH_KV"
id = "c3d5b52df4574046936f9bea334b696e"
